### ISSUE TITLE
Problems with dependency to sp?

### ISSUE THREAD

**Issue by MatthieuStigler** [babichmorrowc/hull2spatial#2]
Hi

Thanks for the package, it seems very interesting!

It seems the imports to  `sp` (`Line` and `Lines`) are not working? See below

Thanks!

``` r
library(alphahull)
#> Registered S3 method overwritten by 'spatstat.geom':
#>   method     from
#>   print.boxx cli
x <- matrix(runif(100), nc = 2)
ahull.obj <- ahull(x, alpha = 0.2)

# devtools::install_github("babichmorrowc/hull2spatial")
library(hull2spatial)
ahull2poly(ahull.obj)
#> Error in Line(coords = coords.xy): could not find function "Line"
```

<sup>Created on 2022-02-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by babichmorrowc** [comment]
Thank you for flagging this! I played around with the DESCRIPTION file and your example is working for me now. If you still have issues with this, please let me know
